#ifndef _LINUX_COMPAT_DEBUG_TRACE_H_
#define _LINUX_COMPAT_DEBUG_TRACE_H_

/*
 * Optional serial bring-up traces. Default off; set to 1 while debugging.
 */

#ifndef LINUX_COMPAT_TRACE_POLL
#define LINUX_COMPAT_TRACE_POLL 0
#endif

#ifndef LINUX_COMPAT_TRACE_VFS_IO
#define LINUX_COMPAT_TRACE_VFS_IO 0
#endif

#ifndef LINUX_COMPAT_TRACE_IPC_WEDGE
#define LINUX_COMPAT_TRACE_IPC_WEDGE 0
#endif

#ifndef LINUX_COMPAT_TRACE_IPC_REPLY_STALL
#define LINUX_COMPAT_TRACE_IPC_REPLY_STALL 0
#endif

#ifndef LINUX_COMPAT_TRACE_IPC_REPLY_STALL_USER
#define LINUX_COMPAT_TRACE_IPC_REPLY_STALL_USER 0
#endif

#ifndef LINUX_COMPAT_TRACE_MMAP_FS
#define LINUX_COMPAT_TRACE_MMAP_FS 0
#endif

#endif /* _LINUX_COMPAT_DEBUG_TRACE_H_ */
