#!/usr/bin/env python3
"""
Copy user test ELFs into rootfs/tests/ and write /tests/manifest for cpio.

Also generates /tests/run_all.sh from the ordered test list (pack-time
expansion). Guest ash must not `while read` a text manifest: that path is
poll + byte VFS READ through nested VFS→cpio IPC — a bring-up hazard on this
kernel's IPC wait model. The test plan is a build artifact.

Usage:
  python3 script/config/pack_user_rootfs.py ARCH ROOT_DIR USER_PAYLOAD_DIR

Reads USER_PAYLOAD_DIR/user/build/ARCH/ for ELF binaries and optional
USER_PAYLOAD_DIR/build/manifest.order (one basename per line), else sorted.
"""

import os
import shutil
import subprocess
import sys


ARCH_STRIP = {
    "aarch64": "aarch64-linux-gnu-strip",
    "x86_64": "x86_64-linux-gnu-strip",
    "riscv64": "riscv64-linux-gnu-strip",
    "loongarch": "loongarch64-linux-gnu-strip",
}


def strip_test_elf(path: str, arch: str) -> None:
    """Drop debug/symbol bloat so ELFs fit kallocator's 2MiB single-chunk limit."""
    strip_bin = ARCH_STRIP.get(arch)
    if not strip_bin:
        return
    try:
        subprocess.run(
            [strip_bin, "--strip-unneeded", path],
            check=True,
            stdout=subprocess.DEVNULL,
            stderr=subprocess.DEVNULL,
        )
    except (OSError, subprocess.CalledProcessError) as exc:
        print(f"WARNING: {strip_bin} failed on {path}: {exc}", file=sys.stderr)


def read_manifest_order(order_file: str, elf_names: list[str]) -> list[str]:
    if not os.path.isfile(order_file):
        return sorted(elf_names)

    ordered: list[str] = []
    seen = set()
    with open(order_file, "r", encoding="utf-8") as f:
        for raw in f:
            name = raw.strip()
            if not name or name.startswith("#"):
                continue
            if name in elf_names and name not in seen:
                ordered.append(name)
                seen.add(name)

    for name in sorted(elf_names):
        if name not in seen:
            ordered.append(name)
    return ordered


# Tests that intentionally exit with a non-zero status (Linux 8-bit).
# Key: basename of /tests/<name>; value: expected $? after wait.
EXPECTED_EXIT_STATUS = {
    "ch2b_exit": 1234 & 0xFF,  # MAGIC=1234 → 210
}


def write_run_all(path: str, test_paths: list[str]) -> None:
    """
    Emit a busybox ash script with an explicit run_one per test.

    Do not use `while read` / `$(cat manifest)` here — ash always poll()+reads
    byte-wise, which stressed nested VFS IPC during bring-up.
    """
    lines = [
        "#!/bin/busybox sh",
        "# Generated by pack_user_rootfs.py — do not edit; regenerate via make user.",
        "# Test plan compiled at pack time (no runtime manifest line-read).",
        "",
        'echo "=== run_all start ==="',
        "fail=0",
        "pass=0",
        "",
        "run_one() {",
        '	t="$1"',
        '	expect="${2:-0}"',
        '	echo "=== $t ==="',
        '	"$t"',
        '	st=$?',
        '	if [ "$st" -eq "$expect" ]; then',
        "		pass=$((pass + 1))",
        "	else",
        '		echo "FAIL $t (status=$st expect=$expect)"',
        "		fail=$((fail + 1))",
        "	fi",
        "}",
        "",
    ]
    for p in test_paths:
        base = os.path.basename(p)
        expect = EXPECTED_EXIT_STATUS.get(base, 0)
        if expect == 0:
            lines.append(f'run_one "{p}"')
        else:
            lines.append(f'run_one "{p}" {expect}')
    lines.extend(
        [
            "",
            'echo "=== run_all done pass=$pass fail=$fail ==="',
            'if [ "$fail" -ne 0 ]; then',
            "	exit 1",
            "fi",
            "exit 0",
            "",
        ]
    )
    with open(path, "w", encoding="utf-8") as f:
        f.write("\n".join(lines))
    os.chmod(path, 0o755)


def main() -> int:
    if len(sys.argv) != 4:
        print(
            "Usage: pack_user_rootfs.py ARCH ROOT_DIR USER_PAYLOAD_DIR",
            file=sys.stderr,
        )
        return 2

    arch = sys.argv[1]
    root_dir = sys.argv[2]
    user_payload_dir = sys.argv[3]

    elf_src_dir = os.path.join(user_payload_dir, "user", "build", arch)
    rootfs_tests = os.path.join(root_dir, "rootfs", "tests")
    manifest_path = os.path.join(rootfs_tests, "manifest")
    run_all_path = os.path.join(rootfs_tests, "run_all.sh")
    order_file = os.path.join(user_payload_dir, "build", "manifest.order")

    if not os.path.isdir(elf_src_dir):
        print(f"ERROR: ELF build dir missing: {elf_src_dir}", file=sys.stderr)
        print("Run: make user ARCH=" + arch, file=sys.stderr)
        return 1

    elf_names = [
        f
        for f in os.listdir(elf_src_dir)
        if os.path.isfile(os.path.join(elf_src_dir, f)) and f != "manifest"
    ]
    if not elf_names:
        print(f"ERROR: no ELF files in {elf_src_dir}", file=sys.stderr)
        return 1

    ordered = read_manifest_order(order_file, elf_names)

    os.makedirs(rootfs_tests, exist_ok=True)

    lines = [
        "# RendezvOS user test manifest — one absolute VFS path per line",
        "# Generated by script/config/pack_user_rootfs.py",
        "# (informational; boot orchestration uses generated run_all.sh)",
        "",
    ]

    test_paths: list[str] = []
    for name in ordered:
        src = os.path.join(elf_src_dir, name)
        dst = os.path.join(rootfs_tests, name)
        shutil.copy2(src, dst)
        strip_test_elf(dst, arch)
        vfs_path = f"/tests/{name}"
        lines.append(vfs_path)
        test_paths.append(vfs_path)

    with open(manifest_path, "w", encoding="utf-8") as mf:
        mf.write("\n".join(lines) + "\n")

    write_run_all(run_all_path, test_paths)
    print(f"Generated {run_all_path} ({len(test_paths)} tests)")

    smoke_src = os.path.join(root_dir, "script", "rootfs", "boot_smoke.sh")
    smoke_dst = os.path.join(rootfs_tests, "boot_smoke.sh")
    if os.path.isfile(smoke_src):
        shutil.copy2(smoke_src, smoke_dst)
        os.chmod(smoke_dst, 0o755)
        print(f"Copied boot script → {smoke_dst}")
    else:
        print(f"WARNING: boot script missing: {smoke_src}", file=sys.stderr)

    print(f"Packed {len(ordered)} test ELF(s) into {rootfs_tests}")
    print(f"Wrote {manifest_path}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
