#!/usr/bin/env python3
"""
Copy user test ELFs into rootfs/tests/ and write /tests/manifest for cpio.

Usage:
  python3 script/config/pack_user_rootfs.py ARCH ROOT_DIR USER_PAYLOAD_DIR

Reads USER_PAYLOAD_DIR/user/build/ARCH/ for ELF binaries and
USER_PAYLOAD_DIR/build/manifest.order (if present) or sorted basenames.
"""

import os
import shutil
import subprocess
import sys


ARCH_STRIP = {
    "aarch64": "aarch64-linux-gnu-strip",
    "x86_64": "x86_64-linux-gnu-strip",
    "riscv64": "riscv64-linux-gnu-strip",
    "loongarch": "loongarch64-linux-gnu-strip",
}


def strip_test_elf(path: str, arch: str) -> None:
    """Drop debug/symbol bloat so ELFs fit kallocator's 2MiB single-chunk limit."""
    strip_bin = ARCH_STRIP.get(arch)
    if not strip_bin:
        return
    try:
        subprocess.run(
            [strip_bin, "--strip-unneeded", path],
            check=True,
            stdout=subprocess.DEVNULL,
            stderr=subprocess.DEVNULL,
        )
    except (OSError, subprocess.CalledProcessError) as exc:
        print(f"WARNING: {strip_bin} failed on {path}: {exc}", file=sys.stderr)


def read_manifest_order(order_file: str, elf_names: list[str]) -> list[str]:
    if not os.path.isfile(order_file):
        return sorted(elf_names)

    ordered: list[str] = []
    seen = set()
    with open(order_file, "r", encoding="utf-8") as f:
        for raw in f:
            name = raw.strip()
            if not name or name.startswith("#"):
                continue
            if name in elf_names and name not in seen:
                ordered.append(name)
                seen.add(name)

    for name in sorted(elf_names):
        if name not in seen:
            ordered.append(name)
    return ordered


def main() -> int:
    if len(sys.argv) != 4:
        print(
            "Usage: pack_user_rootfs.py ARCH ROOT_DIR USER_PAYLOAD_DIR",
            file=sys.stderr,
        )
        return 2

    arch = sys.argv[1]
    root_dir = sys.argv[2]
    user_payload_dir = sys.argv[3]

    elf_src_dir = os.path.join(user_payload_dir, "user", "build", arch)
    rootfs_tests = os.path.join(root_dir, "rootfs", "tests")
    manifest_path = os.path.join(rootfs_tests, "manifest")
    order_file = os.path.join(user_payload_dir, "build", "manifest.order")

    if not os.path.isdir(elf_src_dir):
        print(f"ERROR: ELF build dir missing: {elf_src_dir}", file=sys.stderr)
        print("Run: make user ARCH=" + arch, file=sys.stderr)
        return 1

    elf_names = [
        f
        for f in os.listdir(elf_src_dir)
        if os.path.isfile(os.path.join(elf_src_dir, f)) and f != "manifest"
    ]
    if not elf_names:
        print(f"ERROR: no ELF files in {elf_src_dir}", file=sys.stderr)
        return 1

    ordered = read_manifest_order(order_file, elf_names)

    os.makedirs(rootfs_tests, exist_ok=True)

    lines = [
        "# RendezvOS user test manifest — one absolute VFS path per line",
        "# Generated by script/config/pack_user_rootfs.py",
        "",
    ]

    for name in ordered:
        src = os.path.join(elf_src_dir, name)
        dst = os.path.join(rootfs_tests, name)
        shutil.copy2(src, dst)
        strip_test_elf(dst, arch)
        lines.append(f"/tests/{name}")

    with open(manifest_path, "w", encoding="utf-8") as mf:
        mf.write("\n".join(lines) + "\n")

    print(f"Packed {len(ordered)} test ELF(s) into {rootfs_tests}")
    print(f"Wrote {manifest_path}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
